<#
.SYNOPSIS
    Removes the developer-local build configuration from this repository.

.DESCRIPTION
    Deletes build/local.props, the gitignored file generated by
    scripts/prepare-references.ps1 that points MSBuild at the developer's own
    ADOFAI / UMM installation.

    Only repository-local, regenerable build configuration is touched. Nothing
    outside the repository is modified, and no game / UMM file is read or
    copied. Re-run scripts/prepare-references.ps1 to regenerate the file.

.PARAMETER WhatIf
    Print actions without deleting anything.

.EXAMPLE
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\scripts\clean-local-config.ps1 -WhatIf
#>

[CmdletBinding()]
param(
    [switch]$WhatIf
)

$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$localProps = Join-Path $repoRoot 'build\local.props'

function Remove-IfExists([string]$path) {
    if (Test-Path -LiteralPath $path -PathType Leaf) {
        if ($WhatIf) {
            Write-Host "WhatIf: would remove $path"
        } else {
            Remove-Item -LiteralPath $path -Force
            Write-Host "Removed $path"
        }
    } else {
        Write-Host "Skip (not present): $path"
    }
}

Remove-IfExists $localProps

Write-Host 'Done.' -ForegroundColor Cyan
Write-Host 'Re-run scripts/prepare-references.ps1 to regenerate build/local.props.' -ForegroundColor Cyan
